name: flutter_mobile_engineer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  connectivity_plus: ^3.0.2
  http:
  equatable:
  shared_preferences:

  get_it:
  injectable:
  json_annotation:

  chopper:
  logger:

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0

  build_runner:
  freezed:
  chopper_generator:
  injectable_generator:
  json_serializable:
  integration_test:
    sdk: flutter
  mocktail:
  mockito:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

